---
- name: Download distrib vector
  become: true
  get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector-{{ vector_version }}.deb"
    mode: 0755
    timeout: 60
  run_once: True
  register: get_vector
  until: get_vector is succeeded
- name: Install vector deb
  become: true
  ansible.builtin.apt:
    deb: "/tmp/vector-{{ vector_version }}.deb"
    dpkg_options: 'force-confold,force-confdef'
- name: Template it
  become: true
  ansible.builtin.template:
    src: "templates/vector.cfg.j2"
    dest: "{{ vector_home }}"
    backup: True
  register: template_result
  tags: vector_template
#- name: fixing repo for CentOS 8
#  become: true
#  ansible.builtin.copy:
#    src: yum.repos.d
#    dest: /etc
#  when: 
#    - ansible_facts.distribution == "CentOS"
#    - ansible_facts.distribution_major_version == "8"
#- name: Get vector distrib (deb)
#  ansible.builtin.get_url:
#    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
#    dest: "./vector-{{ vector_version }}.dpkg"
#  when: ansible_facts.os_family == "Debian"
#- name: Get vector distrib (rpm)
#  ansible.builtin.get_url:
#    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
#    dest: "./vector-{{ vector_version }}.rpm"
#  when: ansible_facts.os_family == "RedHat"
#- name: Install vector packages (deb)
#  become: true
#  ansible.builtin.apt:
#    deb: ./vector-{{ vector_version }}.dpkg
#  when: ansible_facts.os_family == "Debian"
#  notify: start vector service
#- name: Install vector packages (rpm)
#  become: true
#  ansible.builtin.yum:
#    name: "./vector-{{ vector_version }}.rpm"
#    disable_gpg_check: true
#  when: ansible_facts.os_family == "RedHat"
#  notify: start vector service
---
